"""
VERITAS — ledger.py

Implements two complementary tamper-evidence mechanisms over EPR certificates:

1.  **Hash chain** — each certificate stores SHA-256(prev_hash || cert_bytes) so that
    any retroactive modification invalidates every entry that follows it.  Verified by
    ``verify_chain``.

2.  **Merkle tree** — certificates are committed to a binary Merkle tree so that a
    single certificate can prove its inclusion in the root hash without revealing the
    full dataset.  Generated by ``build_merkle_tree`` / ``get_merkle_proof`` and
    verified by ``verify_merkle_proof``.

All hash operations use SHA-256 via the stdlib ``hashlib`` module.  No third-party
Merkle library is used; the implementation is written from scratch.
"""

from __future__ import annotations

import hashlib
import sqlite3
from typing import Optional


# ---------------------------------------------------------------------------
# Low-level hash helpers
# ---------------------------------------------------------------------------


def _sha256(data: bytes) -> bytes:
    """Return the 32-byte SHA-256 digest of *data*."""
    return hashlib.sha256(data).digest()


def certificate_bytes(cert: dict[str, object]) -> bytes:
    """Return the canonical UTF-8 byte representation of *cert* for hashing.

    The format is strictly::

        f"{id}|{arrival_id}|{facility_id}|{quantity_kg:.6f}|{waste_category}|{minted_at}"

    All fields are taken directly from the certificate dict (keys: ``id``,
    ``arrival_id``, ``facility_id``, ``quantity_kg``, ``waste_category``,
    ``minted_at``).  Field order and the ``:.6f`` precision on ``quantity_kg``
    are invariant — changing either breaks every stored chain hash.
    """
    canonical = (
        f"{cert['id']}|{cert['arrival_id']}|{cert['facility_id']}"
        f"|{float(cert['quantity_kg']):.6f}"  # type: ignore[arg-type]
        f"|{cert['waste_category']}|{cert['minted_at']}"
    )
    return canonical.encode("utf-8")


def hash_chain_entry(previous_hash: bytes, cert: dict[str, object]) -> bytes:
    """Compute the next hash-chain entry.

    Returns SHA-256(``previous_hash`` || ``certificate_bytes(cert)``).
    The concatenation of the previous hash with the certificate bytes binds each
    entry to its predecessor; tampering with any entry invalidates all successors.
    """
    return _sha256(previous_hash + certificate_bytes(cert))


# ---------------------------------------------------------------------------
# Hash chain — persistence
# ---------------------------------------------------------------------------

_GENESIS_HASH: bytes = b"\x00" * 32


def append_to_chain(
    db: sqlite3.Connection,
    cert_id: str,
) -> str:
    """Compute the new hash-chain entry for *cert_id* and persist it.

    Algorithm:

    1. Fetch the certificate row from the DB.
    2. Find the immediately preceding certificate (by ``minted_at`` ascending,
       then ``id`` as a tiebreaker) and read its ``ledger_hash_hex``.
       If this is the first certificate use the 32-byte genesis hash (all zeros).
    3. Compute ``new_hash = hash_chain_entry(prev_hash_bytes, cert_row)``.
    4. ``UPDATE certificates SET ledger_hash_hex=? WHERE id=?``.
    5. Return the new hash as a lowercase hex string.

    :param db: An open SQLite connection with the VERITAS schema.
    :param cert_id: Primary key of the certificate to append.
    :returns: Hex-encoded 64-character SHA-256 hash string.
    :raises sqlite3.OperationalError: If the certificate is not found.
    """
    db.row_factory = sqlite3.Row
    cur = db.cursor()

    # 1. Fetch the target certificate
    cur.execute(
        "SELECT id, arrival_id, facility_id, quantity_kg, waste_category, minted_at "
        "FROM certificates WHERE id = ?",
        (cert_id,),
    )
    row = cur.fetchone()
    if row is None:
        raise sqlite3.OperationalError(f"Certificate not found: {cert_id!r}")
    cert: dict[str, object] = dict(row)

    # 2. Fetch the previous certificate's hash (ordered by minted_at, then id)
    cur.execute(
        """
        SELECT ledger_hash_hex
        FROM   certificates
        WHERE  (minted_at, id) < (?, ?)
        ORDER  BY minted_at DESC, id DESC
        LIMIT  1
        """,
        (cert["minted_at"], cert_id),
    )
    prev_row = cur.fetchone()

    if prev_row is None or prev_row["ledger_hash_hex"] in ("", None):
        # First certificate ever — use genesis hash
        prev_hash_bytes: bytes = _GENESIS_HASH
    else:
        prev_hash_bytes = bytes.fromhex(str(prev_row["ledger_hash_hex"]))

    # 3. Compute new chain hash
    new_hash = hash_chain_entry(prev_hash_bytes, cert)
    new_hash_hex = new_hash.hex()

    # 4. Persist
    cur.execute(
        "UPDATE certificates SET ledger_hash_hex = ? WHERE id = ?",
        (new_hash_hex, cert_id),
    )
    db.commit()

    return new_hash_hex


def verify_chain(
    db: sqlite3.Connection,
    from_cert_id: Optional[str] = None,
    to_cert_id: Optional[str] = None,
) -> bool:
    """Verify the hash chain is unbroken over the specified range.

    Iterates every certificate in ascending ``(minted_at, id)`` order between
    *from_cert_id* and *to_cert_id* (both inclusive, ``None`` means open-ended).
    For each certificate the expected hash is recomputed from scratch; if the
    stored ``ledger_hash_hex`` does not match, the function returns ``False``
    immediately.

    :param db: An open SQLite connection with the VERITAS schema.
    :param from_cert_id: Start of the range (inclusive); ``None`` = genesis.
    :param to_cert_id: End of the range (inclusive); ``None`` = latest.
    :returns: ``True`` if the entire chain verifies; ``False`` on any mismatch.
    """
    db.row_factory = sqlite3.Row
    cur = db.cursor()

    # Determine minted_at bounds for the requested range
    from_ts: Optional[str] = None
    to_ts: Optional[str] = None

    if from_cert_id is not None:
        cur.execute("SELECT minted_at FROM certificates WHERE id = ?", (from_cert_id,))
        r = cur.fetchone()
        if r is None:
            return False
        from_ts = str(r["minted_at"])

    if to_cert_id is not None:
        cur.execute("SELECT minted_at FROM certificates WHERE id = ?", (to_cert_id,))
        r = cur.fetchone()
        if r is None:
            return False
        to_ts = str(r["minted_at"])

    # Build query — fetch all certs in the range in chronological order
    query = (
        "SELECT id, arrival_id, facility_id, quantity_kg, waste_category, "
        "minted_at, ledger_hash_hex "
        "FROM certificates "
    )
    conditions: list[str] = []
    params: list[str] = []

    if from_ts is not None:
        conditions.append("(minted_at, id) >= (?, ?)")
        params.extend([from_ts, from_cert_id])  # type: ignore[list-item]

    if to_ts is not None:
        conditions.append("(minted_at, id) <= (?, ?)")
        params.extend([to_ts, to_cert_id])  # type: ignore[list-item]

    if conditions:
        query += "WHERE " + " AND ".join(conditions) + " "

    query += "ORDER BY minted_at ASC, id ASC"

    cur.execute(query, params)
    rows = cur.fetchall()

    if not rows:
        # Empty range is vacuously valid
        return True

    # If starting from genesis, previous hash is all-zeros; otherwise we need
    # the hash of the cert immediately before the range.
    if from_cert_id is None:
        running_hash: bytes = _GENESIS_HASH
    else:
        # Find the cert just before the first one in our range
        first = rows[0]
        cur.execute(
            """
            SELECT ledger_hash_hex
            FROM   certificates
            WHERE  (minted_at, id) < (?, ?)
            ORDER  BY minted_at DESC, id DESC
            LIMIT  1
            """,
            (str(first["minted_at"]), str(first["id"])),
        )
        prev = cur.fetchone()
        if prev is None or prev["ledger_hash_hex"] in ("", None):
            running_hash = _GENESIS_HASH
        else:
            running_hash = bytes.fromhex(str(prev["ledger_hash_hex"]))

    for row in rows:
        cert: dict[str, object] = dict(row)
        expected = hash_chain_entry(running_hash, cert)
        stored_hex = str(cert.get("ledger_hash_hex", ""))
        if stored_hex != expected.hex():
            return False
        running_hash = expected

    return True


# ---------------------------------------------------------------------------
# Merkle tree — in-memory
# ---------------------------------------------------------------------------


def build_merkle_tree(leaves: list[bytes]) -> list[list[bytes]]:
    """Build a binary Merkle tree from *leaves* and return all levels.

    The returned list has ``levels[0]`` as the leaf level and
    ``levels[-1]`` as a single-element list containing the root.

    Special cases:

    * **Empty list** — returns ``[[b'\\x00' * 32]]`` (a genesis root).
    * **Odd number of nodes** at any level — the last node is duplicated
      before hashing the pair.

    Internal node hash: SHA-256(left_child || right_child).

    :param leaves: Pre-hashed leaf values (each 32 bytes, but not enforced).
    :returns: List of levels; index 0 = leaf level, last index = root level.
    """
    if not leaves:
        return [[b"\x00" * 32]]

    current_level = list(leaves)
    levels: list[list[bytes]] = [current_level]

    while len(current_level) > 1:
        next_level: list[bytes] = []
        # Duplicate last node if count is odd
        if len(current_level) % 2 == 1:
            current_level = current_level + [current_level[-1]]
        for i in range(0, len(current_level), 2):
            parent = _sha256(current_level[i] + current_level[i + 1])
            next_level.append(parent)
        current_level = next_level
        levels.append(current_level)

    return levels


def get_merkle_root(leaves: list[bytes]) -> bytes:
    """Return the Merkle root bytes for *leaves*.

    :param leaves: Pre-hashed leaf values.
    :returns: 32-byte root hash.
    """
    return build_merkle_tree(leaves)[-1][0]


def get_merkle_proof(leaves: list[bytes], index: int) -> list[dict[str, str]]:
    """Generate a Merkle inclusion proof for the leaf at *index*.

    :param leaves: Pre-hashed leaf values used to build the tree.
    :param index: 0-based index of the leaf to prove.
    :returns: Ordered list of sibling hashes, each as::

            {"hash": "<64-char hex>", "direction": "left" | "right"}

        where ``"direction"`` is the side of the *sibling* relative to the
        current node.  To recompute the parent:

        * ``direction == "right"`` → parent = SHA-256(current || sibling)
        * ``direction == "left"``  → parent = SHA-256(sibling || current)

    :raises IndexError: If *index* is out of range.
    :raises ValueError: If *leaves* is empty.
    """
    if not leaves:
        raise ValueError("Cannot generate proof for an empty leaf list")
    if index < 0 or index >= len(leaves):
        raise IndexError(f"Leaf index {index} out of range [0, {len(leaves)})")

    levels = build_merkle_tree(leaves)
    proof: list[dict[str, str]] = []
    current_index = index

    for level in levels[:-1]:  # skip root level
        # Pad to even length (mirrors build_merkle_tree)
        if len(level) % 2 == 1:
            level = level + [level[-1]]

        if current_index % 2 == 0:
            # current is left child; sibling is to the right
            sibling_index = current_index + 1
            direction = "right"
        else:
            # current is right child; sibling is to the left
            sibling_index = current_index - 1
            direction = "left"

        proof.append({"hash": level[sibling_index].hex(), "direction": direction})
        current_index //= 2

    return proof


def verify_merkle_proof(
    leaf: bytes,
    proof: list[dict[str, str]],
    root: bytes,
) -> bool:
    """Verify a Merkle inclusion proof.

    Traverses *proof* from *leaf* toward the root, computing parent hashes at
    each step.  Returns ``True`` only if the final computed hash equals *root*
    exactly.  Any tampered leaf, proof node, or root causes ``False``.

    :param leaf: The 32-byte leaf hash to verify.
    :param proof: Ordered sibling list as returned by :func:`get_merkle_proof`.
    :param root: Expected 32-byte Merkle root.
    :returns: ``True`` if verified; ``False`` otherwise.
    """
    current = leaf
    for step in proof:
        sibling = bytes.fromhex(step["hash"])
        if step["direction"] == "right":
            current = _sha256(current + sibling)
        else:
            current = _sha256(sibling + current)
    return current == root


# ---------------------------------------------------------------------------
# Certificate proof (combined chain + Merkle)
# ---------------------------------------------------------------------------


def get_certificate_proof(
    db: sqlite3.Connection,
    cert_id: str,
) -> dict[str, object]:
    """Return a combined chain-hash + Merkle proof bundle for *cert_id*.

    Fetches **all** certificates from the database (ordered by ``minted_at``,
    ``id`` ascending), builds a Merkle tree over their leaf hashes, and
    generates a Merkle proof for the requested certificate.  The ``valid``
    field is ``True`` only when:

    * The certificate exists.
    * Its Merkle proof verifies against the computed root.

    Returned structure::

        {
            "certificate_id": str,
            "leaf_hash":      "<64-char hex>",    # SHA-256(certificate_bytes)
            "proof":          list[dict],          # from get_merkle_proof
            "merkle_root":    "<64-char hex>",
            "chain_hash":     "<64-char hex>",     # stored ledger_hash_hex
            "valid":          bool,
        }

    :param db: An open SQLite connection with the VERITAS schema.
    :param cert_id: Primary key of the certificate to prove.
    :returns: Proof bundle dict as described above.
    :raises sqlite3.OperationalError: If *cert_id* is not found in the DB.
    """
    db.row_factory = sqlite3.Row
    cur = db.cursor()

    # Fetch all certs in deterministic order
    cur.execute(
        "SELECT id, arrival_id, facility_id, quantity_kg, waste_category, "
        "minted_at, ledger_hash_hex "
        "FROM certificates "
        "ORDER BY minted_at ASC, id ASC"
    )
    all_rows = cur.fetchall()

    if not all_rows:
        raise sqlite3.OperationalError(f"Certificate not found: {cert_id!r}")

    # Build ordered list of cert dicts and locate the target
    all_certs: list[dict[str, object]] = [dict(r) for r in all_rows]
    target_index: Optional[int] = None
    for i, c in enumerate(all_certs):
        if c["id"] == cert_id:
            target_index = i
            break

    if target_index is None:
        raise sqlite3.OperationalError(f"Certificate not found: {cert_id!r}")

    target = all_certs[target_index]

    # Leaf hashes = SHA-256(certificate_bytes) for each cert
    leaf_hashes: list[bytes] = [_sha256(certificate_bytes(c)) for c in all_certs]
    target_leaf = leaf_hashes[target_index]

    # Build Merkle tree and proof
    root = get_merkle_root(leaf_hashes)
    proof = get_merkle_proof(leaf_hashes, target_index)
    proof_valid = verify_merkle_proof(target_leaf, proof, root)

    # Also verify the stored chain hash matches the recomputed value.
    # The Merkle proof only covers certificate_bytes() (which excludes
    # ledger_hash_hex), so a corrupted chain hash would pass the Merkle
    # check undetected.  We recompute from the predecessor's hash here.
    if target_index == 0:
        prev_hash_bytes: bytes = _GENESIS_HASH
    else:
        prev_stored = str(all_certs[target_index - 1].get("ledger_hash_hex", ""))
        if prev_stored in ("", None):
            prev_hash_bytes = _GENESIS_HASH
        else:
            prev_hash_bytes = bytes.fromhex(prev_stored)

    expected_chain_hash = hash_chain_entry(prev_hash_bytes, target)
    stored_chain_hash = str(target.get("ledger_hash_hex", ""))
    chain_hash_valid = stored_chain_hash == expected_chain_hash.hex()

    return {
        "certificate_id": cert_id,
        "leaf_hash": target_leaf.hex(),
        "proof": proof,
        "merkle_root": root.hex(),
        "chain_hash": stored_chain_hash,
        "valid": proof_valid and chain_hash_valid,
    }
